# H2
spring.h2.console:
    enabled: true
    path: /h2

# Datasource
spring:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/db2
    username: sa
    password:
    driver-class-name: org.h2.Driver